name: Bemis
favicon: null
layout_spectrum: 0.39662
typography_spectrum: 0.34864
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#84cfde'
    - '#131313'
    - '#dacec6'
    - '#493635'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
