name: Bemis
favicon: null
layout_spectrum: 0.57488
typography_spectrum: 0.2716
title: 'Todd Bemis :: Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b4d9df'
    - '#2a292f'
    - '#9e865a'
    - '#d63a23'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
