name: Bemis
favicon: null
layout_spectrum: 0.57488
typography_spectrum: 0.2716
title: 'Todd Bemis :: Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3d801'
    - '#01698c'
    - '#444444'
    - '#ffffff'
    - '#329e7a'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
