name: Bemis
favicon: null
layout_spectrum: 0.6264488447923213
typography_spectrum: 0.7526569236069918
title: 'Todd Bemis :: Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.1875
  lightness: 0.6801549117080867
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
