name: Bemis
favicon: null
layout_spectrum: 0.39662
typography_spectrum: 0.34864
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3d801'
    - '#01698c'
    - '#444444'
    - '#ffffff'
    - '#329e7a'
  brandStrength: 0.1875
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
